version: '3.8'

services:
  postgress:
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_USER: edwin
      POSTGRES_PASSWORD: edwin123
      POSTGRES_DB: school
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  app:
    build: .
    container_name: nextjs_app
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL: postgresql://edwin:edwin123@localhost:5432/school
    depends_on:
      - postgres

volumes:
  postgres_data: